var data = {
    "nodes": [
        {"id": "Sam", "group":"main"},
        {"id": "Diana"},
        {"id": "Emily"},
        {"id": "Kelly"},
        {"id": "Rebecca"},
        {"id": "Alexis"},
        {"id": "Preston"},
        {"id": "Nicole"},
        {"id": "Ellie"},
        {"id": "Faith"},
        {"id": "Emma"},
        {"id": "Biden"},
        {"id": "Kamala Harris"},
        {"id": "Angelina Jolie"},
        {"id": "Kevin"},
        {"id": "Ellen"},
        {"id": "Taylor"},
        {"id": "Reanna"},
        {"id": "Flora"},
        {"id": "Eli"},
        {"id": "Jack"},
        {"id": "Richard"},
        {"id": "Aaron"},
        {"id": "Gwendolyn"},
        {"id": "Kaelyn"},
        {"id": "Marina"},
        {"id": "Megan"},
        {"id": "Katie D"},
        {"id": "Elizabeth"},
        {"id": "Hope"},
        {"id": "Sarah Anne"},
        {"id": "Riley"},
        {"id": "Sarah"},
        {"id": "Arja"},
        {"id": "Reynolds"},
        {"id": "Hellena Bodham Carter"},
        {"id": "Sam P"},
        {"id": "Priya"},
        {"id": "Jenna"},
        {"id": "Patrick"},
        {"id": "Caroline"},
        {"id": "David"},
        {"id": "Gabe"},
        {"id": "Megan W"},
        {"id": "Lesley"},
        {"id": "Gui"},
        {"id": "Stuti"},
        {"id": "Ashley"},
        {"id": "Elenor"},
        {"id": "Simon"},
        {"id": "Alice"},
        {"id": "Miranda"},
        {"id": "Steph"},
        {"id": "Libba"},
        {"id": "Abby"},
        {"id": "Jasmine"},
        {"id": "Cristina"},
        {"id": "Zain"},
        {"id": "Maddie"},
        {"id": "Brenna"},
        {"id": "Olivia"},
        {"id": "Ale"},
        {"id": "Chloe"},
        {"id": "Florence"},
        {"id": "Corrie"},
        {"id": "Max"},
        {"id": "Khan"},
        {"id": "Gigi"},
        {"id": "Nymisha"},
        {"id": "Julie"},
        {"id": "Wendy"},
        {"id": "Nasiha"},
        {"id": "Mayra"},
        {"id": "Jackie"},
        {"id": "Madeline"},
        {"id": "Alex"},
        {"id": "Teddy Roosevelt"},
        {"id": "President Ivan"},
        {"id": "Elizabeth Warren"},
        {"id": "Samia"},
        {"id": "Nima"},
        {"id":"Brianna"}
    ],
    "edges": [
      { "from": "Sam", "to": "Diana" },
      { "from": "Sam", "to": "Emily" },
      { "from": "Sam", "to": "Kelly" },
      { "from": "Sam", "to": "Rebecca" },
      { "from": "Sam", "to": "Alexis" },
      { "from": "Sam", "to": "Preston" },

      { "from": "Diana", "to": "Emily" },
      { "from": "Diana", "to": "Kelly" },
      { "from": "Diana", "to": "Rebecca" },
      { "from": "Diana", "to": "Alexis" },
      { "from": "Diana", "to": "Preston" },

      { "from": "Emily", "to": "Kelly" },
      { "from": "Emily", "to": "Rebecca" },
      { "from": "Emily", "to": "Alexis" },

      { "from": "Kelly", "to": "Rebecca" },
      { "from": "Kelly", "to": "Alexis" },
      { "from": "Kelly", "to": "Preston" },

      { "from": "Rebecca", "to": "Alexis" },

      { "from": "Diana", "to": "Ellie" },
      { "from": "Diana", "to": "Patrick" },
      { "from": "Diana", "to": "David" },
      { "from": "Diana", "to": "Jenna" },
      { "from": "Diana", "to": "Megan W" },
      { "from": "Diana", "to": "Stuti" },
      { "from": "Diana", "to": "Alice" },
      { "from": "Diana", "to": "Miranda" },
      { "from": "Diana", "to": "Abby" },
      { "from": "Diana", "to": "Brianna" },
      { "from": "Diana", "to": "Ale" },
      { "from": "Diana", "to": "Olivia" },
      { "from": "Diana", "to": "Chloe" },
      { "from": "Diana", "to": "Aaron" },
      { "from": "Diana", "to": "Reynolds" },
      { "from": "Diana", "to": "Gigi" },
      { "from": "Diana", "to": "Nymisha" },
      { "from": "Diana", "to": "Julie" },
      { "from": "Diana", "to": "Sam P" },
      { "from": "Diana", "to": "Nasiha" },
      { "from": "Diana", "to": "Nicole" },
      { "from": "Diana", "to": "Arja" },
      { "from": "Diana", "to": "Riley"},
      { "from": "Diana", "to": "Priya"},
      { "from": "Diana", "to": "Alex"},
      { "from": "Diana", "to": "Mayra"},
      { "from": "Diana", "to": "Maddie"},
      { "from": "Diana", "to": "Cristina"},
      { "from": "Diana", "to": "Samia"},
      { "from": "Diana", "to": "Nima"},


      { "from": "Sam", "to": "Emma"},
      { "from": "Sam", "to": "Nicole"},
      { "from": "Sam", "to": "Ellie"},
      { "from": "Sam", "to": "Taylor"},
      { "from": "Sam", "to": "Richard"},
      { "from": "Sam", "to": "Gwendolyn"},
      { "from": "Sam", "to": "Aaron"},
      { "from": "Sam", "to": "Kaelyn"},
      { "from": "Sam", "to": "Marina"},
      { "from": "Sam", "to": "Megan"},
      { "from": "Sam", "to": "Katie D"},
      { "from": "Sam", "to": "Elizabeth"},
      { "from": "Sam", "to": "Hope"},
      { "from": "Sam", "to": "Riley"},
      { "from": "Sam", "to": "Sarah Anne"},
      { "from": "Sam", "to": "Sarah"},
      { "from": "Sam", "to": "Arja"},
      { "from": "Sam", "to": "Priya"},
      { "from": "Sam", "to": "Reynolds"},
      { "from": "Sam", "to": "Madeline"},
      { "from": "Sam", "to": "Sam P"},

      { "from": "Reynolds", "to": "Hellena Bodham Carter"},
      { "from": "Biden", "to": "Kamala Harris"},
      { "from": "Biden", "to": "Elizabeth Warren"},
      { "from": "Biden", "to": "Preston"},
      { "from": "Elizabeth Warren", "to": "Kamala Harris"},
      { "from": "Aaron", "to": "Elizabeth Warren"},
      { "from": "Alice", "to": "Teddy Roosevelt"},
      { "from": "Alice", "to": "President Ivan"},
      { "from": "Biden", "to": "President Ivan"},
      { "from": "Preston", "to": "Angelina Jolie"},

      { "from": "Nasiha", "to": "Sam P"},
      { "from": "Nasiha", "to": "Olivia"},
      { "from": "Nasiha", "to": "Julie"},
      { "from": "Nasiha", "to": "Gigi"},
      { "from": "Nasiha", "to": "Nymisha"},
      { "from": "Nasiha", "to": "Wendy"},
      { "from": "Nasiha", "to": "Khan"},
      { "from": "Nasiha", "to": "Mayra"},
      { "from": "Nasiha", "to": "Alex"},
      { "from": "Nasiha", "to": "Priya"},
      { "from": "Nasiha", "to": "Arja"},
      { "from": "Nasiha", "to": "Nima"},
      { "from": "Nasiha", "to": "Max"},
      { "from": "Nasiha", "to": "Jasmine"},

      { "from": "Gigi", "to": "Nicole"},
      { "from": "Gigi", "to": "Olivia"},
      { "from": "Gigi", "to": "Zain"},
      { "from": "Gigi", "to": "Jasmine"},
      { "from": "Gigi", "to": "Maddie"},
      { "from": "Gigi", "to": "Brenna"},
      { "from": "Gigi", "to": "Corrie"},
      { "from": "Gigi", "to": "Khan"},
      { "from": "Gigi", "to": "Arja"},
      { "from": "Gigi", "to": "Nima"},
      { "from": "Gigi", "to": "Nymisha"},
      { "from": "Gigi", "to": "Wendy"},
      { "from": "Gigi", "to": "Flora"},
      { "from": "Gigi", "to": "Alex"},
      { "from": "Gigi", "to": "Priya"},

      { "from": "Priya", "to": "Julie"},
      { "from": "Priya", "to": "Olivia"},
      { "from": "Priya", "to": "Khan"},
      { "from": "Priya", "to": "Wendy"},
      { "from": "Priya", "to": "Mayra"},
      { "from": "Priya", "to": "Jasmine"},
      { "from": "Priya", "to": "Alex"},
      { "from": "Priya", "to": "Madeline"},
      { "from": "Priya", "to": "Jackie"},
      { "from": "Priya", "to": "Arja"},
      { "from": "Priya", "to": "Riley"},
      { "from": "Priya", "to": "Lesley"}
    ]
}